import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { FaReact } from "react-icons/fa";
import { LuGraduationCap } from "react-icons/lu";
import libraryImg from "@/public/Library.jpg";
import creditImg from "@/public/Credit.jpg";
import hardwareImg from "@/public/Hardware.jpg";
import buddyImg from "@/public/Buddy.jpg";
import healthappimg from "@/public/HospitalApp.jpeg";
import leaveImg from "@/public/Leave.jpg";

export const links = [
  {
    name: "Home",
    hash: "#home",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  {
    name: "Experience",
    hash: "#experience",
  },
  {
    name: "Contact",
    hash: "#contact",
  },
] as const;

export const experiencesData = [
  {
    title: "Intern Software Engineer",
    location: "X-ONT Software (Pvt) Ltd.",
    description: "Gained hands-on experience in software development using ASP.NET, Angular, MS SQL Server, and Crystal Reports.Trained on the company’s base application “Ventura”, contributing to feature development and system enhancements.",
    icon: React.createElement(LuGraduationCap),
    date: "2025 Feb- 2025 Sep",
  },

  {
    title: "Freelancer Developer",
    location: "Full Time",
    description: "I'm currently working as a full-stack freelance developer. My core stack includes React, Angular, .NET, TypeScript, Tailwind,Mui, MSSQL.. I am actively seeking full-time opportunities.",
    icon: React.createElement(FaReact),
    date: "2025 - present",
  },
] as const;

export const projectsData = [
  {
    title: "Hospital Management System",
    description: "•	Collaborated on a web-based system to manage hospital operations and patient records.",
    tags: [".Net 7","ReactJS", "MS SQL Server", "Material UI", "Entity Framework", "Azure", "Vercel"],
    imageUrl: healthappimg,
    link: '',
  },
  {
    title: "Leave Application-Internship project",
    description: "•	Independently implemented the Employee Leave Entry workflow, including validation and database integration",
    tags: ["Angular 19","NET 8", "MS SQL Server", "IIS", "Entity Framework"],
    imageUrl: leaveImg,
    link: "",
  },
  {
    title: "Library Management System",
    description: "Developed a secure full-stack library management system with authentication, role-based authorization, and database-driven workflows",
    tags: ["Angular","ASP.NET", "Ms SQL", "JWT","Entity Framework Core"],
    imageUrl: libraryImg,
    link: '',
  },
  {
    title: "Credit Card Fraud Detection (AI Model)",
    description: "•	Built an ML-based fraud detection system achieving good accuracy on transactions using ensemble learning algorithms.",
    tags: ["Python", "Scikit-learn", "Pandas", "NumPy", "Jupyter Notebook"],
    imageUrl: creditImg,
    link: '',
  },
  {
    title: "Pharmacy Storage Assistant (Robot)",
    description: "•	Developed a robot to automatically retrieve medicines based on lists generated by a web application.",
    tags: ["Arduino", "ESP8266", "C++,", "ReactJS", "sensors"],
    imageUrl: hardwareImg,
    link: '',
  },
   {
    title: "BuddyBot – AI Chatbot",
    description: "•	•	Developed an AI-powered chatbot with a React frontend and a Python FastAPI backend to handle user queries and generate intelligent responses",
    tags: ["React", "Python", "FastAPI,", "Groq API ", "REST API"],
    imageUrl: buddyImg,
    link: '',
  },
] as const;

export const skillsData = [
  "React",
  "Angular",
  "Material UI",
  ".NET",
  "Entity Framework",
  "Flutter",
  " React Native",
  "Dart",
  "C#",
  "C",
  "Java",
  "TypeScript",
  "Azure",
  "Vercel",
  "IIS",
  "HTML",
  "CSS",
  "JavaScript",
  "Next.js",
  "Node.js",
  "Crystal Reports",
  "Git",
  "Docker",
  "MsSql",
  "MySQL",
  "Pandas",
  "NumPy",
  "Scikit-Learn",
  "jupyter Notebook",
  "SpringBoot",
  "Python",
] as const;
